#! /usr/bin/bash 

source student_transcrpt.sh
source subject_statistics.sh
source top_student.sh
source failing_student.sh
source fullGrade_matrix.sh

function reports_statistics() {
   while true; do
        echo "=================================="
        echo " Please choose from the menu below:"
        echo "=================================="
    select choice in "Student Transcript + GPA" "Subject Statistics"  "Top Students by GPA" "Failing Students Report" "Full Grade Matrix" "back"
    do
        case $choice in
            "Student Transcript + GPA")  student_transcript  ;; 
            "Subject Statistics") subject_statistics ;;
            "Top Students by GPA") top_student ;; 
            "Failing Students Report") failing_students  ;; 
            "Full Grade Matrix") fullGrade_matrix  ;; 
            "back") return ;;
            *) echo "Invalid choice" ;;
        esac
    done
    done
}

